package(
    default_visibility = ["//visibility:public"],
)

cc_library(
    name="serialize_tuple",
    srcs=[
        "serialize_tuple.h"
    ],
    visibility=[  # Change this entry for compability
        "//visibility:public"
    ]
)
